import Navbar from '@/components/ui/navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Analytics } from '@vercel/analytics/react'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const revalidate = 3600

export const metadata: Metadata = {
  title: 'Artistic Twin Designs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <hr className="divide-solid" />
        {children}
        <hr className="divide-solid" />
        <Footer />
      </body>
      <Analytics />
    </html>
  )
}
